# Generated by Django 3.1.7 on 2023-10-26 17:54

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200, verbose_name='Titulo')),
                ('direccion', models.CharField(max_length=200, verbose_name='Direccion')),
                ('comuna', models.CharField(max_length=200, verbose_name='Comuna')),
                ('region', models.CharField(max_length=50, verbose_name='Region')),
                ('descripcion', models.TextField()),
                ('img', models.ImageField(upload_to='cards/')),
                ('fecha', models.DateField()),
                ('cupos', models.IntegerField()),
                ('inscritos', models.IntegerField(default=0)),
                ('activo', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Card',
                'verbose_name_plural': 'Cards',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre del club')),
                ('abreviado', models.CharField(max_length=10, verbose_name='Nombre abreviado')),
                ('direccion', models.CharField(max_length=200, verbose_name='Direccion')),
                ('comuna', models.CharField(max_length=50, verbose_name='Comuna')),
                ('ciudad', models.CharField(max_length=50, verbose_name='Ciudad')),
                ('correo', models.EmailField(blank=True, max_length=200, null=True, verbose_name='Correo electronico')),
                ('telefono', models.IntegerField(blank=True, null=True, verbose_name='Telefono')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Club',
                'verbose_name_plural': 'Clubes',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Front',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('img', models.ImageField(upload_to='front/')),
                ('titulo', models.CharField(blank=True, max_length=200, null=True)),
                ('contenido', models.TextField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
                ('file', models.FileField(blank=True, max_length=254, upload_to='front/files/')),
            ],
            options={
                'verbose_name': 'Front',
                'verbose_name_plural': 'Fronts',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('img', models.ImageField(upload_to='galeria/')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Galeria',
                'verbose_name_plural': 'Galerias',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('parrafo', models.TextField()),
                ('img', models.ImageField(upload_to='links/')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Link',
                'verbose_name_plural': 'Links',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('img', models.ImageField(upload_to='noticias/')),
                ('fecha', models.DateField()),
                ('resumen', models.CharField(max_length=200)),
                ('info', models.TextField()),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='titulo')),
                ('is_active', models.BooleanField(default=False, verbose_name='Activo')),
                ('is_aprobado', models.BooleanField(default=False, verbose_name='Aprobado')),
                ('is_pendiente', models.BooleanField(default=True, verbose_name='Pendiente')),
                ('img1', models.ImageField(blank=True, upload_to='noticias/')),
                ('img2', models.ImageField(blank=True, upload_to='noticias/')),
                ('img3', models.ImageField(blank=True, upload_to='noticias/')),
                ('img4', models.ImageField(blank=True, upload_to='noticias/')),
                ('img5', models.ImageField(blank=True, upload_to='noticias/')),
                ('lugar', models.CharField(blank=True, max_length=200)),
                ('comentario', models.TextField(default='Sin comentario')),
            ],
            options={
                'verbose_name': 'Noticia',
                'verbose_name_plural': 'Noticias',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('perfil', models.CharField(max_length=30, verbose_name='Perfil de usuario')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripcion del perfil')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfiles',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=200, verbose_name='Tipo')),
                ('descripcion', models.TextField()),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Tipo',
                'verbose_name_plural': 'Tipos',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rut', models.CharField(max_length=10, verbose_name='Rut')),
                ('primer_nombre', models.CharField(max_length=200, verbose_name='Primer nombre')),
                ('segundo_nombre', models.CharField(max_length=200, verbose_name='Segundo nombre')),
                ('apellido_paterno', models.CharField(max_length=200, verbose_name='Apellido paterno')),
                ('apellido_materno', models.CharField(max_length=200, verbose_name='Apellido materno')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
                ('correo', models.EmailField(max_length=200, verbose_name='Correo electronico')),
                ('telefono', models.IntegerField(verbose_name='Telefono movil')),
                ('sexo', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], default='M', max_length=1)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo'), ('S', 'Suspendido')], default='A', max_length=1)),
                ('order', models.IntegerField(default=0)),
                ('perfil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.perfil', verbose_name='Perfil de usuario')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Listado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('img', models.ImageField(upload_to='listado/')),
                ('order', models.IntegerField(default=0)),
                ('tipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.tipo', verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Listado',
                'verbose_name_plural': 'Listados',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Campeonato',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre del campeonato')),
                ('fecha', models.DateField(verbose_name='Fecha de torneo')),
                ('bases', models.FileField(upload_to='bases/')),
                ('order', models.IntegerField(default=0)),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.club', verbose_name='Club')),
            ],
            options={
                'verbose_name': 'Campeonato',
                'verbose_name_plural': 'Campeonatos',
                'ordering': ['order'],
            },
        ),
    ]
