# Generated by Django 4.2.6 on 2023-10-10 19:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=200)),
                ('titulo', models.CharField(max_length=200)),
                ('img', models.ImageField(upload_to='links/')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Listado',
                'verbose_name_plural': 'Listados',
                'ordering': ['order'],
            },
        ),
    ]
