# Generated by Django 3.1.7 on 2023-10-28 17:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Torneo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200, verbose_name='Titulo')),
                ('direccion', models.CharField(max_length=200, verbose_name='Direccion')),
                ('region', models.CharField(choices=[('I', 'Región de Tarapacá  '), ('II', 'Región de Antofagasta  '), ('III', 'Región de Atacama  '), ('IV', 'Región de Coquimbo  '), ('V', 'Región de Valparaíso    '), ('VI', 'Región del Libertador General Bernardo O’Higgins    '), ('VII', 'Región del Maule    '), ('VIII', 'Región del Bio-bío  '), ('IX', 'Región de La Araucanía  '), ('X', 'Región de Los Lagos '), ('XI', 'Región Aysén del General Carlos Ibáñez del Campo '), ('XII', 'Región de Magallanes y Antártica Chilena   '), ('XIII', 'Región Metropolitana de Santiago    '), ('XIV', 'Región de Los Ríos '), ('XV', 'Región de Arica y Parinacota   '), ('XVI', 'Región de Ñuble ')], default='XIII', max_length=50, verbose_name='Region')),
                ('descripcion', models.TextField(blank=True)),
                ('img', models.ImageField(upload_to='torneo/')),
                ('fecha', models.DateField()),
                ('cupos', models.IntegerField()),
                ('inscritos', models.IntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('proximo', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Torneo',
                'verbose_name_plural': 'Torneos',
                'ordering': ['order'],
            },
        ),
        migrations.DeleteModel(
            name='Card',
        ),
        migrations.AlterModelOptions(
            name='listado',
            options={'ordering': ['tipo', 'order'], 'verbose_name': 'Listado', 'verbose_name_plural': 'Listados'},
        ),
    ]
