# Generated by Django 3.1.7 on 2023-10-29 23:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20231029_1937'),
    ]

    operations = [
        migrations.CreateModel(
            name='NormaRegla',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripcion del perfil')),
                ('archivo', models.FileField(upload_to='normas_reglas/')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Norma_Regla',
                'verbose_name_plural': 'Normas_Reglas',
                'ordering': ['titulo', 'order'],
            },
        ),
    ]
