# Generated by Django 3.1.7 on 2023-10-28 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20231028_1718'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='torneo',
            options={'ordering': ['-proximo', 'activo', 'fecha'], 'verbose_name': 'Torneo', 'verbose_name_plural': 'Torneos'},
        ),
    ]
