# Generated by Django 4.2.6 on 2023-10-11 12:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_listado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Tipo',
                'verbose_name_plural': 'Tipos',
                'ordering': ['order'],
            },
        ),
        migrations.AlterField(
            model_name='listado',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.tipo'),
        ),
    ]
