# Generated by Django 4.2.6 on 2023-10-11 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_tipo_alter_listado_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listado',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.tipo', verbose_name='Tipo'),
        ),
    ]
