# Generated by Django 3.1.7 on 2023-11-02 16:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_normaregla'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuotaAnual',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('año', models.DateField()),
                ('monto_cuota', models.IntegerField()),
                ('monto_descuento', models.IntegerField()),
                ('monto_cargo', models.IntegerField()),
                ('fecha_creacion', models.DateField(verbose_name='Fecha de pago')),
                ('order', models.IntegerField(default=0)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.usuario', verbose_name='socio club')),
            ],
            options={
                'verbose_name': 'CuotaAnual',
                'verbose_name_plural': 'CuotasAnuales',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Cuota',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mes', models.CharField(choices=[('ENE', 'Enero'), ('FEB', 'Febrero'), ('MAR', 'Marzo'), ('ABR', 'Abril'), ('MAY', 'Mayo'), ('JUN', 'Junio'), ('JUL', 'Julio'), ('AGO', 'Agosto'), ('SEP', 'Septiembre'), ('OCT', 'Octubre'), ('NOV', 'Noviembre'), ('DIC', 'Diciembre')], default='Ene', max_length=3)),
                ('año', models.DateField()),
                ('monto_descuento', models.IntegerField()),
                ('monto_cargo', models.IntegerField()),
                ('monto_pago', models.IntegerField()),
                ('fecha_pago', models.DateField(verbose_name='Fecha de pago')),
                ('estado_pago', models.CharField(choices=[('P', 'Pendiente'), ('C', 'Cancelado')], default='P', max_length=1, verbose_name='Estado de la cuota')),
                ('order', models.IntegerField(default=0)),
                ('monto_cuota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.cuotaanual')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.usuario', verbose_name='socio club')),
            ],
            options={
                'verbose_name': 'Cuota',
                'verbose_name_plural': 'Cuotas',
                'ordering': ['order'],
            },
        ),
    ]
