# Generated by Django 4.2.6 on 2023-10-11 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_listado_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listado',
            name='img',
            field=models.ImageField(upload_to='listado/'),
        ),
    ]
