# Generated by Django 3.1.7 on 2023-10-28 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_noticia_region'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noticia',
            old_name='lugar',
            new_name='direccion',
        ),
    ]
