# Generated by Django 3.1.7 on 2023-11-02 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20231102_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuotaanual',
            name='año',
            field=models.IntegerField(verbose_name='Año cuotas'),
        ),
    ]
