# Generated by Django 3.1.7 on 2023-11-12 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_listado_actual'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='perfil',
        ),
        migrations.DeleteModel(
            name='Perfil',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
