# Generated by Django 3.1.7 on 2023-11-02 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20231102_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuotaanual',
            name='descripcion',
            field=models.CharField(default='cgm', max_length=30),
        ),
    ]
