# Generated by Django 4.2.6 on 2023-10-11 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_alter_listado_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipo',
            name='tipo',
            field=models.CharField(max_length=200, verbose_name='Tipo'),
        ),
    ]
