# Generated by Django 3.1.7 on 2023-11-03 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_cuotaanual_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuota',
            name='año',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='cuotaanual',
            name='año',
            field=models.PositiveIntegerField(verbose_name='Año cuotas'),
        ),
    ]
