# Generated by Django 4.2.6 on 2023-10-12 12:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_alter_tipo_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200, verbose_name='Titulo')),
                ('sub_titulo', models.CharField(max_length=200, verbose_name='Sub Titulo')),
                ('direccion', models.CharField(max_length=200, verbose_name='Direccion')),
                ('comuna', models.CharField(max_length=200, verbose_name='Comuna')),
                ('region', models.CharField(max_length=50, verbose_name='Region')),
                ('descripcion', models.TextField()),
                ('img', models.ImageField(upload_to='cards/')),
                ('fecha', models.DateField()),
                ('cupos', models.IntegerField()),
                ('inscritos', models.IntegerField(default=0)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Card',
                'verbose_name_plural': 'Cards',
                'ordering': ['order'],
            },
        ),
    ]
