# Generated by Django 4.2.6 on 2023-10-12 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='activo',
            field=models.BooleanField(default=False),
        ),
    ]
