# Generated by Django 3.1.7 on 2023-11-09 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_auto_20231107_2305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuotaanual',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='cuotaanual',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='cuotaanual',
            name='monto_cargo',
        ),
        migrations.RemoveField(
            model_name='cuotaanual',
            name='monto_descuento',
        ),
        migrations.RemoveField(
            model_name='cuotaanual',
            name='usuario',
        ),
        migrations.AlterField(
            model_name='cuota',
            name='año',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.cuotaanual'),
        ),
        migrations.AlterField(
            model_name='cuota',
            name='fecha_pago',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de pago'),
        ),
        migrations.AlterField(
            model_name='cuota',
            name='mes',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cuota',
            name='monto_cargo',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='cuota',
            name='monto_descuento',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='cuota',
            name='monto_pago',
            field=models.PositiveIntegerField(),
        ),
    ]
