# Generated by Django 4.2.6 on 2023-10-12 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_card_activo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='sub_titulo',
        ),
    ]
