# Generated by Django 3.1.7 on 2023-10-15 00:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_remove_card_sub_titulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('perfil', models.CharField(max_length=30, verbose_name='Perfil de usuario')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripcion del perfil')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfiles',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rut', models.CharField(max_length=10, verbose_name='Rut')),
                ('primer_nombre', models.CharField(max_length=200, verbose_name='Primer nombre')),
                ('segundo_nombre', models.CharField(max_length=200, verbose_name='Segundo nombre')),
                ('apellido_paterno', models.CharField(max_length=200, verbose_name='Apellido paterno')),
                ('apellido_materno', models.CharField(max_length=200, verbose_name='Apellido materno')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
                ('correo', models.EmailField(max_length=200, verbose_name='Correo electronico')),
                ('telefono', models.IntegerField(verbose_name='Telefono movil')),
                ('sexo', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], default='M', max_length=1)),
                ('fecha_creacion', models.DateField()),
                ('estado', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo'), ('S', 'Suspendido')], default='A', max_length=1)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['order'],
            },
        ),
    ]
