# Generated by Django 3.1.7 on 2023-11-09 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_auto_20231108_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuota',
            name='monto_descuento',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
