# Generated by Django 3.1.7 on 2023-10-15 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_usuario_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='fecha_creacion',
            field=models.DateField(auto_now_add=True),
        ),
    ]
