# Generated by Django 3.1.7 on 2023-10-15 17:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_auto_20231014_2159'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre del club')),
                ('abreviado', models.CharField(max_length=10, verbose_name='Nombre abreviado')),
                ('direccion', models.CharField(max_length=200, verbose_name='Direccion')),
                ('comuna', models.CharField(max_length=50, verbose_name='Comuna')),
                ('ciudad', models.CharField(max_length=50, verbose_name='Ciudad')),
                ('correo', models.EmailField(blank=True, max_length=200, null=True, verbose_name='Correo electronico')),
                ('telefono', models.IntegerField(blank=True, null=True, verbose_name='Telefono')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Club',
                'verbose_name_plural': 'Clubes',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Campeonato',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre del campeonato')),
                ('fecha', models.DateField(verbose_name='Fecha de torneo')),
                ('bases', models.ImageField(upload_to='bases/')),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.club', verbose_name='Club')),
            ],
        ),
    ]
