# Generated by Django 3.1.7 on 2023-10-15 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_campeonato_club'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campeonato',
            options={'ordering': ['order'], 'verbose_name': 'Campeonato', 'verbose_name_plural': 'Campeonatos'},
        ),
        migrations.AddField(
            model_name='campeonato',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
