# Generated by Django 3.1.7 on 2023-10-15 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_auto_20231015_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campeonato',
            name='bases',
            field=models.FileField(upload_to='bases/'),
        ),
    ]
