# Generated by Django 4.2.6 on 2023-10-23 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_auto_20231015_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listado',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.tipo', verbose_name='Tipo'),
        ),
    ]
