# Generated by Django 3.1.7 on 2023-10-23 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_auto_20231015_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='front',
            name='file',
            field=models.FileField(blank=True, max_length=254, upload_to='front/files/'),
        ),
    ]
