# Generated by Django 4.2.6 on 2023-10-23 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_alter_listado_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='front',
            name='contenido',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='front',
            name='titulo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
